import {useEffect,useRef,useState} from 'react';
import {BookmarkPlus,Mic,Paperclip,Send,Square,Trash2} from 'lucide-react';
import {useAgentSession,type ImageAttachment} from '../agent/session';
import {imageFile} from '../agent/images';
import {disposeRecognition,disposeRecording} from '../agent/voice-lifecycle';
import {chooseRecorderMime,SCRIBE_MODEL,scribeHttpError,scribeMediaFacts} from '../agent/scribe';

type SpeechCtor=new()=>{continuous:boolean;interimResults:boolean;lang:string;start():void;stop():void;onresult?:(e:{results:ArrayLike<{0:{transcript:string};isFinal:boolean}>})=>void;onerror?:(e:{error:string})=>void;onend?:()=>void};
const promptsKey='gucos2:saved-prompts';
export const VOICE_RECORDING_MAX_MS=5*60_000;
export const VOICE_RECORDING_MAX_BYTES=12*1024*1024;
const VOICE_RECORDING_TIMESLICE_MS=1_000;

export default function ChatComposer(){
 const session=useAgentSession(),[value,setValue]=useState(''),[images,setImages]=useState<ImageAttachment[]>([]),[drag,setDrag]=useState(false),[error,setError]=useState(''),[listening,setListening]=useState(false),[prompts,setPrompts]=useState<string[]>(()=>{try{return JSON.parse(localStorage.getItem(promptsKey)||'[]')}catch{return[]}});
 const ref=useRef<HTMLTextAreaElement>(null),fileRef=useRef<HTMLInputElement>(null),submitRef=useRef(false),recognition=useRef<InstanceType<SpeechCtor>|null>(null),recorder=useRef<{media:MediaRecorder;stream:MediaStream;chunks:Blob[];abort:AbortController;timer?:number}|null>(null),mounted=useRef(true),skipDraftPersist=useRef(true),voiceBase=useRef(''),voiceFinal=useRef(''),draftKey=`gucos2:draft:${session.thread?.id??'new'}`;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;disposeRecognition(recognition.current);recognition.current=null;disposeRecording(recorder.current);recorder.current=null}},[]);
 useEffect(()=>{skipDraftPersist.current=true;setValue(localStorage.getItem(draftKey)||'');setImages([])},[draftKey]);
 useEffect(()=>{if(skipDraftPersist.current){skipDraftPersist.current=false;return}localStorage.setItem(draftKey,value)},[draftKey,value]);
 useEffect(()=>{if(ref.current){ref.current.style.height='auto';ref.current.style.height=`${Math.min(160,ref.current.scrollHeight)}px`}},[value]);
 const add=async(files:FileList|File[])=>{setError('');const compress=localStorage.getItem('gucos2:image-compress')!=='false',max=Number(localStorage.getItem('gucos2:image-max')||1048576);try{const added:ImageAttachment[]=[];for(const file of Array.from(files))added.push(await imageFile(file,compress,max));setImages(v=>[...v,...added])}catch(e){setError(String(e))}};
 const submitContent=async(text=value,pending=images)=>{if(submitRef.current||session.streaming||(!text.trim()&&!pending.length))return;submitRef.current=true;setValue('');setImages([]);localStorage.removeItem(draftKey);try{await session.send(text,pending)}catch(e){setValue(text);setImages(pending);setError(String(e))}finally{submitRef.current=false}};
 const toggleVoice=async()=>{
  if(listening){recognition.current?.stop();recorder.current?.media.stop();setListening(false);return}
  setError('');const mode=localStorage.getItem('gucos2:stt-mode')||'web-speech';
  if(mode==='elevenlabs'){
   const key=localStorage.getItem('gucos2:elevenlabs-key')?.trim();if(!key){setError('Save an ElevenLabs key in Settings first');return}
   try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});if(!mounted.current){stream.getTracks().forEach(t=>t.stop());return}const negotiated=chooseRecorderMime(type=>MediaRecorder.isTypeSupported(type)),media=new MediaRecorder(stream,negotiated?{mimeType:negotiated}:{}),chunks:Blob[]=[],abort=new AbortController(),base=value,startTime=performance.now();let bytes=0,stopReason='';const stopBounded=(reason:string)=>{if(media.state==='inactive')return;stopReason=reason;media.stop()};media.ondataavailable=e=>{if(!e.data.size)return;if(bytes+e.data.size>VOICE_RECORDING_MAX_BYTES){stopBounded(`Voice recording reached the ${Math.round(VOICE_RECORDING_MAX_BYTES/1024/1024)} MiB limit; transcribing the captured audio.`);return}chunks.push(e.data);bytes+=e.data.size};media.onstop=async()=>{const active=recorder.current;if(active?.timer)clearTimeout(active.timer);stream.getTracks().forEach(t=>t.stop());if(mounted.current){setListening(false);if(stopReason)setError(stopReason)}try{if(performance.now()-startTime<100)throw new Error('Recording too short (minimum 100ms)');const actualType=media.mimeType||chunks.find(chunk=>chunk.type)?.type||'',facts=scribeMediaFacts(actualType),blob=new Blob(chunks,{type:actualType});if(!blob.size)throw new Error('Recording is empty');const filename=`speech.${facts.extension}`,requestFacts=`${filename}, ${actualType}, ${blob.size} bytes, ${SCRIBE_MODEL}`,form=new FormData();form.append('file',blob,filename);form.append('model_id',SCRIBE_MODEL);const response=await fetch('https://api.elevenlabs.io/v1/speech-to-text',{method:'POST',signal:abort.signal,headers:{'xi-api-key':key},body:form});if(!response.ok)throw await scribeHttpError(response,key,requestFacts);const body=await response.json() as {text?:unknown};if(typeof body.text!=='string'||!body.text.trim())throw new Error(`ElevenLabs returned no transcription (${requestFacts})`);const combined=`${base}${base?' ':''}${body.text}`.trim();if(mounted.current){setValue(combined);if(localStorage.getItem('gucos2:voice-auto-submit')!=='false')void submitContent(combined,images)}}catch(e){if(mounted.current&&!abort.signal.aborted)setError(e instanceof Error?e.message:String(e))}finally{if(recorder.current?.media===media)recorder.current=null}};const timer=window.setTimeout(()=>stopBounded('Voice recording reached the 5 minute limit; transcribing it now.'),VOICE_RECORDING_MAX_MS);recorder.current={media,stream,chunks,abort,timer};media.start(VOICE_RECORDING_TIMESLICE_MS);setListening(true)}catch(e){if(mounted.current)setError(e instanceof Error?e.message:String(e))}
   return
  }
  const speechWindow=window as unknown as {SpeechRecognition?:SpeechCtor;webkitSpeechRecognition?:SpeechCtor},Ctor=speechWindow.SpeechRecognition??speechWindow.webkitSpeechRecognition;if(!Ctor){setError('Web Speech recognition is unavailable in this browser');return}
  voiceBase.current=value;voiceFinal.current='';const r=new Ctor();r.continuous=true;r.interimResults=true;r.lang=navigator.language;r.onresult=e=>{let final='';for(let i=0;i<e.results.length;i++)if(e.results[i].isFinal)final+=e.results[i][0].transcript;voiceFinal.current=final.trim();const combined=`${voiceBase.current}${voiceBase.current&&voiceFinal.current?' ':''}${voiceFinal.current}`;setValue(combined)};r.onerror=e=>setError(`Speech recognition: ${e.error}`);r.onend=()=>{setListening(false);const combined=`${voiceBase.current}${voiceBase.current&&voiceFinal.current?' ':''}${voiceFinal.current}`.trim();if(combined&&localStorage.getItem('gucos2:voice-auto-submit')!=='false')void submitContent(combined,images)};recognition.current=r;r.start();setListening(true)
 };
 const savePrompt=()=>{const p=value.trim();if(!p||prompts.includes(p))return;const next=[...prompts,p];setPrompts(next);localStorage.setItem(promptsKey,JSON.stringify(next))};
 return <form className={`relative border-t border-border bg-background px-3 py-2 safe-bottom ${drag?'ring-2 ring-inset ring-primary':''}`} onSubmit={e=>{e.preventDefault();void submitContent()}} onDragEnter={e=>{e.preventDefault();setDrag(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{if(e.currentTarget===e.target)setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);void add(e.dataTransfer.files)}} data-testid="chat-composer" aria-label="Message composer">
  {drag&&<div className="pointer-events-none absolute inset-0 z-10 grid place-items-center bg-primary/10 text-sm font-medium" data-testid="image-drop-overlay">Drop images to attach</div>}
  {images.length>0&&<div className="mx-auto mb-2 flex max-w-2xl gap-2 overflow-x-auto" aria-label="Pending image attachments">{images.map((image,i)=><div key={`${image.name}-${i}`} className="relative shrink-0"><img src={`data:${image.mediaType};base64,${image.data}`} alt={image.name} className="size-16 rounded border object-cover"/><button type="button" onClick={()=>setImages(v=>v.filter((_,j)=>j!==i))} aria-label={`Remove ${image.name}`} className="absolute -right-1 -top-1 rounded-full bg-background p-1 shadow"><Trash2 className="size-3"/></button></div>)}</div>}
  <div className="mx-auto flex max-w-2xl items-end gap-2"><div className="flex-1"><textarea ref={ref} value={value} onChange={e=>setValue(e.target.value)} onPaste={e=>{const files=Array.from(e.clipboardData.files).filter(f=>f.type.startsWith('image/'));if(files.length){e.preventDefault();void add(files)}}} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&matchMedia('(min-width: 640px)').matches){e.preventDefault();void submitContent()}}} rows={1} placeholder={session.streaming?'Draft your next message while the agent works…':'Message the agent…'} aria-label="Message" className="max-h-40 w-full resize-none rounded-lg border bg-background px-3 py-2 text-base" data-testid="chat-input"/>
   <div className="mt-1 flex flex-wrap items-center gap-1"><input ref={fileRef} type="file" accept="image/*" multiple hidden onChange={e=>{if(e.target.files)void add(e.target.files);e.target.value=''}}/><button type="button" onClick={()=>fileRef.current?.click()} aria-label="Attach images" title="Attach images" className="grid size-9 place-items-center rounded hover:bg-accent"><Paperclip className="size-5"/></button><button type="button" onClick={()=>void toggleVoice()} aria-pressed={listening} aria-label={listening?'Stop voice input':'Start voice input'} className={`grid size-9 place-items-center rounded hover:bg-accent ${listening?'bg-destructive text-white':''}`} data-testid="voice-input"><Mic className="size-5"/></button><button type="button" onClick={savePrompt} disabled={!value.trim()} aria-label="Save current text as prompt" className="grid size-9 place-items-center rounded hover:bg-accent disabled:opacity-30"><BookmarkPlus className="size-5"/></button>{prompts.length>0&&<select aria-label="Saved prompts" defaultValue="" onChange={e=>{setValue(e.target.value);e.currentTarget.value=''}} className="h-9 max-w-40 rounded border bg-background px-2 text-xs"><option value="">Saved prompts…</option>{prompts.map((p,i)=><option key={i} value={p}>{p.slice(0,40)}</option>)}</select>}</div>
  </div>{session.streaming?<button type="button" onClick={session.stop} className="grid size-11 place-items-center rounded-lg bg-destructive text-white" aria-label="Stop turn" data-testid="chat-stop"><Square className="size-5"/></button>:<button type="submit" disabled={!value.trim()&&!images.length} className="grid size-11 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-40" aria-label="Send message" data-testid="chat-send"><Send className="size-5"/></button>}</div>
  {error&&<div role="alert" className="mx-auto mt-1 max-w-2xl text-xs text-destructive">{error}</div>}<div className="sr-only" aria-live="polite">{listening?'Listening for speech':''}</div>
 </form>
}
