import {renderToStaticMarkup} from 'react-dom/server';
import {describe,expect,it,vi} from 'vitest';
import {Markdown} from './Markdown';
import {MessageBlocks,UserBlocks} from './MessageBlocks';

vi.mock('react-syntax-highlighter',()=>({Prism:({children,language}:{children:string;language?:string})=><pre data-language={language}><code>{children}</code></pre>}));
vi.mock('react-syntax-highlighter/dist/esm/styles/prism',()=>({oneDark:{}}));

describe('Chat rich content',()=>{
 it('renders GFM tables, safe external links, inline code, and escapes hostile HTML',()=>{const html=renderToStaticMarkup(<Markdown>{'| A | B |\n|---|---|\n| 1 | 2 |\n\n[site](https://example.com) and `inline` <script>alert(1)</script>'}</Markdown>);expect(html).toContain('<table class=');expect(html).toContain('overflow-x-auto');expect(html).toContain('target="_blank"');expect(html).toContain('rel="noopener noreferrer"');expect(html).toContain('<code');expect(html).not.toContain('<script>');expect(html).toContain('&lt;script&gt;alert(1)&lt;/script&gt;')});
 it('renders complete long code with a language label and guards an incomplete streaming fence',()=>{const long='x'.repeat(5000),complete=renderToStaticMarkup(<Markdown>{`\`\`\`js\n${long}\n\`\`\``}</Markdown>),partial=renderToStaticMarkup(<Markdown>{'```js\nconst x = 1'}</Markdown>);expect(complete).toContain('JavaScript');expect(complete).toContain(long);expect(partial).toContain('streaming…');expect(partial).toContain('data-fence-closed="false"');expect(partial).toContain('const x = 1')});
 it('discloses thinking, specialized tools, honest failures, and unknown blocks',()=>{const html=renderToStaticMarkup(<MessageBlocks content={[{type:'thinking',thinking:'private reasoning',signature:'sig'},{type:'tool_use',id:'a',name:'Edit',input:{path:'a',old_text:'old',new_text:'new'}},{type:'tool_result',tool_use_id:'a',status:'not_run',is_error:true,content:'Not run'},{type:'future_block',payload:{x:1}}]}/>);expect(html).toContain('Thinking');expect(html).toContain('Edit');expect(html).toContain('not run');expect(html).toContain('Unknown block:');expect(html).toContain('future_block')});
 it('groups the entire consecutive non-text run across multiple thinking/tool/result rounds',()=>{const html=renderToStaticMarkup(<MessageBlocks content={[{type:'thinking',thinking:'one'},{type:'tool_use',name:'Bash',input:{command:'one'}},{type:'tool_result',status:'completed',content:'one'},{type:'thinking',thinking:'two'},{type:'tool_use',name:'Read',input:{path:'two'}},{type:'tool_result',status:'completed',content:'two'},{type:'text',text:'answer'}]}/>);expect(html.match(/data-testid="thinking-tool-group"/g)).toHaveLength(1);expect(html).toContain('2 Thinking, 2 Tool Calls, 2 Results');expect(html).toContain('answer')});
 it('renders authored user text literally without assistant prose or Markdown interpretation',()=>{const html=renderToStaticMarkup(<UserBlocks content={[{type:'text',text:'**literal**\nnext'}]}/>);expect(html).toContain('whitespace-pre-wrap');expect(html).toContain('**literal**');expect(html).not.toContain('prose');expect(html).not.toContain('<strong>')});
 it('maps relative workspace files honestly without hijacking external or escaping links',()=>{const html=renderToStaticMarkup(<Markdown>{'[local](notes.txt) [absolute](/root/agent/src/a.c) [outside](../secret) [web](https://example.com/x)'}</Markdown>);expect(html).toContain('href="/edit/root/agent/notes.txt"');expect(html).toContain('href="/edit/root/agent/src/a.c"');expect(html).toContain('href=""');expect(html).toContain('href="https://example.com/x"')});
});
