import {useState} from 'react';
import {Brain,ChevronDown,ChevronRight,Clipboard,FilePenLine,FileSearch,FileText,FolderSearch,ListTree,Terminal,TriangleAlert,Wrench} from 'lucide-react';
import {CodeBlock} from './CodeBlock';
import {Markdown} from './Markdown';

type Block=Record<string,unknown>;
const text=(v:unknown)=>typeof v==='string'?v:'',preview=(s:string,n=90)=>s.replace(/\s+/g,' ').trim().slice(0,n)||'No preview';
export function toolResultPreview(raw:string,parsed:unknown){
 if(parsed&&typeof parsed==='object'){
  const value=parsed as Block,primary=text(value.stdout)||text(value.stderr)||text(value.content??value.text);
  if(primary)return preview(primary);
  if(Array.isArray(value.entries))return preview(value.entries.map(entry=>typeof entry==='string'?entry:JSON.stringify(entry)).join(' · '));
  if(Array.isArray(value.matches))return preview(value.matches.map(entry=>typeof entry==='string'?entry:JSON.stringify(entry)).join(' · '));
 }
 return preview(raw);
}
function Json({value}:{value:unknown}){return <details className="rounded border bg-muted/20 p-2 text-xs"><summary className="cursor-pointer">Raw JSON</summary><pre className="mt-2 max-h-72 overflow-auto whitespace-pre-wrap break-all">{JSON.stringify(value,null,2)}</pre></details>}
// Disclosure is always user-driven: streaming never auto-opens a thinking
// block (or its enclosing group). `active` only styles the card that belongs
// to the round currently streaming (violet pulse + "Thinking…"), so the user
// can still see which block is live while it stays collapsed. Plain
// useState(false) is sufficient because the article's stable turnId identity
// (agent/scroll.ts messageKey) keeps this component mounted across streaming
// → finalize → next round, so a user-opened disclosure persists through
// completion with no effect machinery, and toggling after completion is just
// setState.
function Thinking({block,active}:{block:Block;active:boolean}){const[open,setOpen]=useState(false),body=text(block.thinking);return <div className={`rounded-lg border ${active?'border-violet-400/50 bg-violet-500/5':'bg-muted/20'}`} data-testid="thinking-card"><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex w-full items-center gap-2 p-2 text-left"><Brain className={`size-4 ${active?'animate-pulse text-violet-500':'text-muted-foreground'}`}/>{open?<ChevronDown className="size-3.5"/>:<ChevronRight className="size-3.5"/>}<span className="text-xs font-medium">{active?'Thinking…':'Thinking'}</span>{!open&&<span className="min-w-0 truncate text-xs text-muted-foreground">{preview(body)}</span>}</button>{open&&<div className="border-t px-3 py-2 text-sm text-muted-foreground" data-testid="thinking-body"><Markdown>{body}</Markdown>{Boolean(block.signature)&&<div className="mt-2 text-[10px]" title={text(block.signature)}>Signed thinking · signature preserved</div>}</div>}</div>}
const TOOL_META:Record<string,{Icon:typeof Terminal;label:string}>={Bash:{Icon:Terminal,label:'Run command'},Read:{Icon:FileText,label:'Read file'},Write:{Icon:FilePenLine,label:'Write file'},Edit:{Icon:FilePenLine,label:'Edit file'},List:{Icon:ListTree,label:'List directory'},Search:{Icon:FolderSearch,label:'Search files'}};
function ToolBody({name,input}:{name:string;input:Block}){
 if(name==='Bash')return <CodeBlock className="language-bash">{text(input.command)}</CodeBlock>;
 if(name==='Edit')return <div className="space-y-2"><div className="font-mono text-xs">{text(input.path)}</div><div className="grid gap-2 sm:grid-cols-2"><div className="min-w-0 rounded border border-red-400/30 bg-red-500/5 p-2"><div className="mb-1 text-xs text-red-500">− before</div><pre className="max-h-56 overflow-auto whitespace-pre-wrap text-xs">{text(input.old_text??input.old_string)}</pre></div><div className="min-w-0 rounded border border-green-400/30 bg-green-500/5 p-2"><div className="mb-1 text-xs text-green-600">+ after</div><pre className="max-h-56 overflow-auto whitespace-pre-wrap text-xs">{text(input.new_text??input.new_string)}</pre></div></div></div>;
 if(name==='Write')return <div className="space-y-2"><div className="font-mono text-xs">{text(input.path)}</div><CodeBlock>{text(input.content)}</CodeBlock></div>;
 if(name==='Read')return <dl className="grid grid-cols-[auto_1fr] gap-x-3 text-xs"><dt>Path</dt><dd className="break-all font-mono">{text(input.path)}</dd><dt>Window</dt><dd>{text(input.unit)||'byte'} · offset {String(input.offset??0)} · limit {String(input.limit??'default')}</dd></dl>;
 if(name==='List')return <div className="text-xs"><span className="font-mono">{text(input.path)||'.'}</span> · offset {String(input.offset??0)} · limit {String(input.limit??'default')}</div>;
 if(name==='Search')return <div className="space-y-1 text-xs"><div><FileSearch className="mr-1 inline size-3.5"/><span className="font-mono">{text(input.query)}</span></div><div className="text-muted-foreground">in {text(input.path)||'.'} · offset {String(input.offset??0)} · limit {String(input.limit??'default')}</div></div>;
 return <Json value={input}/>
}
function ToolUse({block}:{block:Block}){const[open,setOpen]=useState(false),name=text(block.name)||'Unknown tool',input=(block.input&&typeof block.input==='object'?block.input:{}) as Block,meta=TOOL_META[name]??{Icon:Wrench,label:'Tool call'},p=name==='Bash'?text(input.command):text(input.path)||text(input.query)||JSON.stringify(input),Icon=meta.Icon;return <div className="rounded-lg border bg-muted/20" data-testid="tool-use" data-tool={name}><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex w-full items-center gap-2 p-2 text-left"><Icon className="size-4 text-muted-foreground"/>{open?<ChevronDown className="size-3.5"/>:<ChevronRight className="size-3.5"/>}<span className="text-xs font-semibold">{name}</span><span className="min-w-0 truncate text-xs text-muted-foreground">{meta.label} · {preview(p)}</span></button>{open&&<div className="border-t p-3"><ToolBody name={name} input={input}/></div>}</div>}
export function ParsedResult({value}:{value:Block}){const stdout=text(value.stdout),stderr=text(value.stderr),content=text(value.content??value.text),entries=Array.isArray(value.entries)?value.entries:undefined,matches=Array.isArray(value.matches)?value.matches:undefined;const truncated=value.stdout_truncated===true||value.stderr_truncated===true||value.stdoutTruncated===true||value.stderrTruncated===true||value.truncated===true,more=value.has_more===true;return <div className="space-y-2 text-xs">{(truncated||more)&&<div className="rounded border border-amber-400/50 bg-amber-500/10 p-2 text-amber-700 dark:text-amber-300" data-testid="tool-result-truncation">{truncated?'Output was truncated at the configured byte cap. Use a narrower follow-up command or window.':'More results remain. Continue with the reported cursor or offset.'}</div>}{stdout&&<div><div className="mb-1 font-medium">stdout</div><CodeBlock>{stdout}</CodeBlock></div>}{stderr&&<div><div className="mb-1 font-medium text-destructive">stderr</div><CodeBlock>{stderr}</CodeBlock></div>}{content&&<CodeBlock>{content}</CodeBlock>}{entries&&<ul className="max-h-72 overflow-auto rounded border font-mono">{entries.map((entry,i)=><li key={i} className="border-b px-2 py-1 last:border-0">{typeof entry==='string'?entry:JSON.stringify(entry)}</li>)}</ul>}{matches&&<ul className="max-h-72 overflow-auto rounded border font-mono">{matches.map((entry,i)=><li key={i} className="border-b px-2 py-1 last:border-0">{typeof entry==='string'?entry:JSON.stringify(entry)}</li>)}</ul>}<dl className="grid grid-cols-[auto_1fr] gap-x-2">{Object.entries(value).filter(([k])=>!['stdout','stderr','content','text','entries','matches'].includes(k)).map(([k,v])=><span className="contents" key={k}><dt className="text-muted-foreground">{k}</dt><dd className="break-all font-mono">{typeof v==='object'?JSON.stringify(v):String(v)}</dd></span>)}</dl></div>}
function ToolResult({block}:{block:Block}){const[open,setOpen]=useState(false),status=text(block.status)||(block.is_error?'error':'completed'),bad=!!block.is_error||['error','aborted','not_run'].includes(status),raw=text(block.content);let parsed:unknown;try{parsed=JSON.parse(raw)}catch{parsed=null}return <div className={`rounded-lg border ${bad?'border-destructive/50 bg-destructive/5':'bg-muted/20'}`} data-testid="tool-result" data-status={status}><button type="button" aria-expanded={open} onClick={()=>setOpen(v=>!v)} className="flex w-full items-center gap-2 p-2 text-left">{bad?<TriangleAlert className="size-4 text-destructive"/>:<Clipboard className="size-4 text-muted-foreground"/>}{open?<ChevronDown className="size-3.5"/>:<ChevronRight className="size-3.5"/>}<span className="rounded border px-1.5 py-0.5 text-[10px] uppercase">{status.replace('_',' ')}</span><span className="min-w-0 truncate text-xs text-muted-foreground">{toolResultPreview(raw,parsed)}</span></button>{open&&<div className="max-h-96 space-y-2 overflow-auto border-t p-3">{parsed&&typeof parsed==='object'?<ParsedResult value={parsed as Block}/>:<Markdown>{raw}</Markdown>}<Json value={parsed??raw}/></div>}</div>}
function Unknown({block}:{block:Block}){return <div className="rounded-lg border border-amber-400/50 bg-amber-500/5 p-2"><div className="mb-2 text-xs font-medium text-amber-600">Unknown block: {text(block.type)||'(missing type)'}</div><Json value={block}/></div>}
function NonText({block,active}:{block:Block;active:boolean}){if(block.type==='thinking')return <Thinking block={block} active={active}/>;if(block.type==='tool_use')return <ToolUse block={block}/>;if(block.type==='tool_result')return <ToolResult block={block}/>;if(block.type==='image'){const source=(block.source&&typeof block.source==='object'?block.source:{}) as Block;return <img src={`data:${text(source.media_type??block.media_type)};base64,${text(source.data??block.data)}`} alt={text(block.alt)||'Attachment'} className="max-h-80 max-w-full rounded-lg border object-contain"/>}return <Unknown block={block}/>}

/** A consecutive non-text run, collapsed by default like cc/c's
 *  ContentBlockGroupView (useState(false)). Streaming never auto-opens it: the
 *  user must open it. The summary's onClick calls preventDefault so React (not
 *  the browser) owns the open attribute. The children stay mounted (rendered
 *  inside <details>) whether open or closed, so ToolUse/ToolResult/Thinking
 *  disclosure state survives a group close and the DOM (and any mutation
 *  observer) sees no removal on collapse. The article's stable turnId identity
 *  means this component is never remounted across streaming → finalize → next
 *  round, so a user-opened group stays open through completion with no effect. */
function ToolGroup({label,errors,testid,children}:{label:string;errors:boolean;testid:string;children:React.ReactNode}){
 const[open,setOpen]=useState(false);
 return <details open={open} className={`rounded-xl border bg-card/40 p-2 ${errors?'border-destructive/30':''}`} data-testid={testid}><summary onClick={e=>{e.preventDefault();setOpen(v=>!v);}} className="cursor-pointer text-xs font-medium">{label}</summary><div className="mt-2 space-y-2">{children}</div></details>
}
export function MessageBlocks({content,streaming=false,activeBlockCount=0}:{content:unknown;streaming?:boolean;activeBlockCount?:number}){
 if(typeof content==='string')return <Markdown>{content}</Markdown>;if(!Array.isArray(content))return <Unknown block={{type:'invalid_content',content}}/>;
 const activeFromIndex=Math.max(0,content.length-(activeBlockCount||0)),isActive=(i:number)=>!!streaming&&i>=activeFromIndex;
 const out:React.ReactNode[]=[];for(let i=0;i<content.length;){const b=(content[i]??{}) as Block;if(b.type==='text'){out.push(<Markdown key={i}>{text(b.text)}</Markdown>);i++;continue}const start=i,run:Block[]=[];while(i<content.length&&text((content[i] as Block)?.type)!=='text')run.push((content[i++]??{}) as Block);const thinking=run.filter(x=>x.type==='thinking').length,calls=run.filter(x=>x.type==='tool_use').length,results=run.filter(x=>x.type==='tool_result').length,other=run.length-thinking-calls-results,errors=run.filter(x=>x.type==='tool_result'&&(x.is_error||x.status!=='completed')).length,parts=[thinking&&`${thinking} Thinking`,calls&&`${calls} Tool Call${calls===1?'':'s'}`,results&&`${results} Result${results===1?'':'s'}`,other&&`${other} Other`].filter(Boolean).join(', ');out.push(<ToolGroup key={`g-${start}`} errors={!!errors} testid={thinking?'thinking-tool-group':'tool-group'} label={`${parts}${errors?` (with ${errors} ${errors===1?'issue':'issues'})`:''}`}>{run.map((block,j)=><NonText key={j} block={block} active={isActive(start+j)}/>)}</ToolGroup>)
 }
 return <div className="space-y-2">{out}</div>
}
export function UserBlocks({content}:{content:unknown}){if(typeof content==='string')return <div className="whitespace-pre-wrap break-words" data-testid="user-text">{content}</div>;if(!Array.isArray(content))return <Unknown block={{type:'invalid_user_content',content}}/>;return <div className="space-y-2">{content.map((raw,i)=>{const block=(raw&&typeof raw==='object'?raw:{type:'invalid_user_block',value:raw}) as Block;if(block.type==='text')return <div key={i} className="whitespace-pre-wrap break-words" data-testid="user-text">{text(block.text)}</div>;if(block.type==='image'){const source=(block.source&&typeof block.source==='object'?block.source:{}) as Block;return <img key={i} src={`data:${text(source.media_type??block.media_type)};base64,${text(source.data??block.data)}`} alt={text(block.alt)||'Attachment'} className="max-h-80 max-w-full rounded-lg border object-contain"/>}if(block.type==='tool_result')return <ToolResult key={i} block={block}/>;return <Unknown key={i} block={block}/>})}</div>}
