import fs from 'node:fs'; import path from 'node:path'; import crypto from 'node:crypto'; import {execFileSync} from 'node:child_process'; import {createRequire} from 'node:module'; import {fileURLToPath} from 'node:url';
const APP=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');let failed=0;const check=(n,c)=>c?console.log('  ok  '+n):(failed++,console.error('  FAIL '+n));
const {preserveImmutableAssets,restoreImmutableAssets}=await import(path.join(APP,'scripts/immutable-dist.mjs'));const retentionRoot=fs.mkdtempSync('/tmp/gucos2-retention-'),oldDist=path.join(retentionRoot,'old'),backup=path.join(retentionRoot,'backup');for(const [p,v] of [['runtime/oldgeneration/os/kernel-worker.js','old-worker'],['runtime/collision/kernel.js','old-collision'],['os/os-system.0123456789abcdef.img','old-image'],['packages/pool/old.tar.gz','old-package'],['index.html','old-mutable']]){const f=path.join(oldDist,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,v);}preserveImmutableAssets(oldDist,backup);fs.rmSync(oldDist,{recursive:true,force:true});for(const [p,v] of [['runtime/newgeneration/kernel.js','new-worker'],['runtime/collision/kernel.js','new-collision']]){const f=path.join(oldDist,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,v);}restoreImmutableAssets(oldDist,backup);check('deploy build retains old immutable runtime, image, and package URLs without overwriting current output',fs.readFileSync(path.join(oldDist,'runtime/oldgeneration/os/kernel-worker.js'),'utf8')==='old-worker'&&fs.readFileSync(path.join(oldDist,'os/os-system.0123456789abcdef.img'),'utf8')==='old-image'&&fs.readFileSync(path.join(oldDist,'packages/pool/old.tar.gz'),'utf8')==='old-package'&&fs.readFileSync(path.join(oldDist,'runtime/newgeneration/kernel.js'),'utf8')==='new-worker'&&fs.readFileSync(path.join(oldDist,'runtime/collision/kernel.js'),'utf8')==='new-collision'&&!fs.existsSync(path.join(oldDist,'index.html')));fs.rmSync(retentionRoot,{recursive:true,force:true});
const require=createRequire(import.meta.url),common=require(path.join(APP,'guc/os/os-common.js')),BLOCK_FS=require(path.join(APP,'guc/host.js')).BLOCK_FS;const repairFs=BLOCK_FS.createV4(new BLOCK_FS.MemoryByteStore(1<<20)),repairMfs=new BLOCK_FS.MountFS({'/':repairFs});common.initRootVolume(repairMfs);repairMfs.unlink('/bin');common.initRootVolume(repairMfs);check('existing root boot repairs a missing merged-usr /bin link',repairMfs.lstat('/bin')!==null&&repairMfs.stat('/bin')===null);let ack=false,closed=false;try{common.appendFileDurable({open:()=>3,write:(_f,_b,n)=>n,fsync:()=>null,close:()=>{closed=true},_lastError:'EIO'},'/journal',new Uint8Array([1]),0o600,true);ack=true}catch{}check('durable append rejects before acknowledgement when fsync fails',!ack&&closed);
const worker=fs.readFileSync(path.join(APP,'guc/os/kernel-worker.js'),'utf8');const kernel=fs.readFileSync(path.join(APP,'guc/kernel.js'),'utf8');const src=fs.readdirSync(path.join(APP,'frontend/src/pages')).filter(f=>f.endsWith('.tsx')).map(f=>fs.readFileSync(path.join(APP,'frontend/src/pages',f),'utf8')).join('\n');
check('legacy os.html source removed',!fs.existsSync(path.join(APP,'guc/os/os.html')));
for(const token of ['wm-canvas','wm-input','screen-resize','OS_COMPOSITOR','wmScene(','wmKey(','wmPointer(','wmSetScreen(','wmFocus(','wmPointerLockChanged('])check(`kernel worker has no desktop handler/call ${token}`,!worker.includes(token));
for(const name of ['surfaceAttach','surfaceKey','surfacePointer','surfacePointerLockChanged'])check(`named low-level ${name} primitive retained`,kernel.includes(`prototype.${name}`));
check('pointer-lock input routes through headless surface seam',worker.includes("ev.kind === 'lockchange') kernel.surfacePointerLockChanged(!!ev.active)"));
check('surface lifecycle is explicit, not discovered by UI interval',worker.includes("type: kind === 'created' ? 'surface-created'")&&!fs.readFileSync(path.join(APP,'frontend/src/components/GraphicalProcessHost.tsx'),'utf8').includes('setInterval'));
check('native prompt and confirm removed from pages',!/(^|[^A-Za-z])(prompt|confirm)\s*\(/m.test(src));
check('frontend has no runtime import from c',!fs.readdirSync(path.join(APP,'frontend/src'),{recursive:true}).filter(String).some(f=>{const p=path.join(APP,'frontend/src',String(f));return fs.statSync(p).isFile()&&/from\s+['"][^'"]*\/c\//.test(fs.readFileSync(p,'utf8'));}));
const layout=fs.readFileSync(path.join(APP,'frontend/src/pages/AppLayout.tsx'),'utf8'),dialog=fs.readFileSync(path.join(APP,'frontend/src/components/Dialog.tsx'),'utf8');
check('c veneer header geometry retained',layout.includes('h-dvh')&&layout.includes('h-8 px-2 rounded-md')&&layout.includes('w-8 h-8 rounded-md')&&layout.includes('hidden sm:inline'));
check('c-style responsive dialog/sheet retained',dialog.includes('place-items-end sm:place-items-center')&&dialog.includes('rounded-t-2xl sm:rounded-lg'));
const pkgSet=JSON.parse(fs.readFileSync(path.join(APP,'package-repository-set.json'),'utf8'));
const defs=fs.readdirSync(path.join(APP,'guc/packages')).filter(f=>f.endsWith('.json')).map(f=>f.slice(0,-5)).sort();
const declaredDefs=[...pkgSet.publishedDefinitions,...(pkgSet.externalDefinitionSources||[]),...pkgSet.siblingToolchainDefinitions].sort();
check('every local package definition is published or an explicit sibling-toolchain definition',JSON.stringify(defs)===JSON.stringify(declaredDefs));
check('every sibling-toolchain definition is mechanically gated',pkgSet.siblingToolchainDefinitions.every(name=>/^native-sibling:(clang|rust)$/.test(JSON.parse(fs.readFileSync(path.join(APP,'guc/packages',name+'.json'),'utf8')).requires||'')));
check('definition and synthesized-companion names are disjoint',![...pkgSet.publishedDefinitions,...pkgSet.siblingToolchainDefinitions].some(n=>pkgSet.publishedSourceCompanions.includes(n)));
const upstreamNames=new Set(pkgSet.upstreamBaseline.definitions);
const upstreamInventory=[...pkgSet.publishedDefinitions,...(pkgSet.externalDefinitionSources||[]),...pkgSet.siblingToolchainDefinitions,...pkgSet.excludedUpstreamDefinitions].filter(n=>upstreamNames.has(n));
const upstreamProvenance=JSON.parse(fs.readFileSync(path.join(APP,'upstream.json'),'utf8'));
const pinnedDefinitions=[...pkgSet.upstreamBaseline.definitions].sort();
const pinnedDigest=crypto.createHash('sha256').update(pinnedDefinitions.join('\n')+'\n').digest('hex');
check('P1 inventory pins the imported upstream commit',pkgSet.upstreamBaseline.commit==='2344fa80d62ad0be6c8184c59c2aeb00ac74142e'&&upstreamProvenance.commit===pkgSet.upstreamBaseline.commit);
check('P1 classifications exactly cover the pinned 38-definition upstream inventory',pkgSet.upstreamBaseline.definitionCount===38&&new Set(pinnedDefinitions).size===38&&pinnedDigest===pkgSet.upstreamBaseline.definitionsSha256&&JSON.stringify(upstreamInventory.sort())===JSON.stringify(pinnedDefinitions));
const siblingUpstream=process.env.GUCOS2_UPSTREAM_REPO;
if(siblingUpstream&&fs.existsSync(path.join(siblingUpstream,'.git'))){
  let tree=[];try{execFileSync('git',['-C',siblingUpstream,'cat-file','-e',pkgSet.upstreamBaseline.commit+'^{commit}']);tree=execFileSync('git',['-C',siblingUpstream,'ls-tree','-r','--name-only',pkgSet.upstreamBaseline.commit,'--','packages'],{encoding:'utf8'}).split('\n').filter(p=>/^packages\/[^/]+\.json$/.test(p)).map(p=>path.basename(p,'.json')).sort();}catch(e){tree=[];}
  check('available sibling checkout matches the pinned upstream definition snapshot',JSON.stringify(tree)===JSON.stringify(pinnedDefinitions));
}else console.log('  info pinned upstream correspondence uses checked-in commit + 38-name SHA-256 snapshot (sibling checkout unavailable)');
const compilerRuntime=['compiler.js','libc-ext.js'].map(f=>fs.readFileSync(path.join(APP,'guc',f),'utf8')).join('\n');
const externalNs=[...new Set([...compilerRuntime.matchAll(/__require_source\(\"([A-Za-z0-9_-]+)\//g)].map(m=>m[1]))].sort();
const publishedNs=[];for(const name of pkgSet.publishedDefinitions){const d=JSON.parse(fs.readFileSync(path.join(APP,'guc/packages',name+'.json'),'utf8'));publishedNs.push(...Object.keys(d.srclib?.src||{}));}
check('every compiler-runtime external __require_source namespace has a published provider',externalNs.every(n=>publishedNs.includes(n))&&externalNs.includes('png')&&externalNs.includes('z'));
if(failed)process.exit(1);console.log('test_source: active graph, headless surface seam, no native dialogs/c imports, c veneer structure passed');
