import { describe, expect, it } from 'vitest'; import { KernelClient } from './kernel-client';
class FakeWorker { onmessage:((e:{data:unknown})=>void)|null=null; onerror:((e:{message:string})=>void)|null=null; onmessageerror:(()=>void)|null=null; sent:unknown[]=[];terminated=false;postMessage(m:unknown){this.sent.push(m)}terminate(){this.terminated=true}emit(data:unknown){this.onmessage?.({data})} crash(message:string){this.onerror?.({message})} }
const host={readClipboard:async()=>'',writeClipboard:async()=>{},saveArtifact:async()=>{}};
function ready(){const w=new FakeWorker();const c=new KernelClient(()=>w as unknown as Worker,()=>true,host);c.boot();w.emit({type:'ready',mode:'test',imageVersion:1,protocolVersion:2});return{w,c}}
describe('KernelClient',()=>{
 it('correlates out-of-order replies with monotonic request ids',async()=>{const{w,c}=ready();const a=c.processes(),b=c.stat('/x');const req=w.sent.slice(-2) as {id:number}[];expect(req[1].id).toBeGreaterThan(req[0].id);w.emit({type:'rpc-result',id:req[1].id,value:null});w.emit({type:'rpc-result',id:req[0].id,value:[]});await expect(a).resolves.toEqual([]);await expect(b).resolves.toBeNull();});
 it('rejects every pending request on worker crash',async()=>{const{w,c}=ready();const a=c.processes(),b=c.stat('/x');w.crash('boom');await expect(a).rejects.toThrow('boom');await expect(b).rejects.toThrow('boom');expect(c.state.status).toBe('fatal');});
 it('does not boot twice under StrictMode-style calls',()=>{const w=new FakeWorker();const c=new KernelClient(()=>w as unknown as Worker,()=>true);c.boot();c.boot();expect(w.sent).toHaveLength(0);});
 it('always acknowledges clipboard freshness and forwards fresh text',async()=>{const w=new FakeWorker(),h={...host,readClipboard:async()=> 'fresh'};const c=new KernelClient(()=>w as unknown as Worker,()=>true,h);c.boot();w.emit({type:'ready',mode:'test',protocolVersion:2});w.emit({type:'clip-read'});await Promise.resolve();await Promise.resolve();expect(w.sent).toContainEqual({type:'clipboard',text:'fresh'});expect(w.sent).toContainEqual({type:'clip-read-done'});});
 it('surfaces clipboard denial but still acknowledges freshness',async()=>{const w=new FakeWorker(),h={...host,readClipboard:async()=>{throw new Error('denied')}};const c=new KernelClient(()=>w as unknown as Worker,()=>true,h);const events:unknown[]=[];c.subscribe(e=>events.push(e));c.boot();w.emit({type:'ready',mode:'test',protocolVersion:2});w.emit({type:'clip-read'});await Promise.resolve();await Promise.resolve();expect(w.sent).toContainEqual({type:'clip-read-done'});expect(events).toContainEqual({type:'host-error',operation:'clipboard-read',message:'denied'});});
 it('rejects an unknown protocol version deliberately',()=>{const w=new FakeWorker();const c=new KernelClient(()=>w as unknown as Worker,()=>true,host);c.boot();w.emit({type:'ready',mode:'test',protocolVersion:1});expect(c.state.status).toBe('fatal');});
 it('terminates the worker and rejects live work before storage recovery',async()=>{const{w,c}=ready(),pending=c.stat('/x');c.prepareStorageReset();expect(w.terminated).toBe(true);expect(c.state).toEqual({status:'booting',message:'Preparing storage recovery…'});await expect(pending).rejects.toThrow('storage recovery');});
 it('carries write clobber-guard options on the wire and resolves the written snapshot',async()=>{const{w,c}=ready();const p=c.write('/root/new.txt',new TextEncoder().encode('hello'),{exclusive:true});const req=w.sent.at(-1) as {id:number;request:Record<string,unknown>};expect(req.request).toMatchObject({op:'fs-write',path:'/root/new.txt',exclusive:true});w.emit({type:'rpc-result',id:req.id,value:{mtimeMs:111,size:5}});await expect(p).resolves.toEqual({mtimeMs:111,size:5});const q=c.write('/root/doc.md',new TextEncoder().encode('body'),{ifUnchanged:{mtimeMs:42,size:9}});const req2=w.sent.at(-1) as {id:number;request:Record<string,unknown>};expect(req2.request).toMatchObject({op:'fs-write',ifUnchanged:{mtimeMs:42,size:9}});w.emit({type:'rpc-result',id:req2.id,value:{mtimeMs:43,size:4}});await q;});
 it('carries the rename noReplace guard on the wire',async()=>{const{w,c}=ready();const p=c.rename('/root/from.txt','/root/to.txt',{noReplace:true});const req=w.sent.at(-1) as {id:number;request:Record<string,unknown>};expect(req.request).toMatchObject({op:'fs-rename',from:'/root/from.txt',to:'/root/to.txt',noReplace:true});w.emit({type:'rpc-result',id:req.id,value:null});await p;});
 it('requests durable mode-0600 append with sync',async()=>{const{w,c}=ready();const p=c.append('/root/.guc/agent/threads/x.jsonl',new TextEncoder().encode('{}\n'));const req=w.sent.at(-1) as {id:number;request:Record<string,unknown>};expect(req.request).toMatchObject({op:'fs-append',path:'/root/.guc/agent/threads/x.jsonl',mode:0o600,sync:true});w.emit({type:'rpc-result',id:req.id,value:null});await expect(p).resolves.toBeNull();});
 it('collects fd-distinguished exec events and exact exit facts',async()=>{const{w,c}=ready();const opening=c.exec('pwd');const req=w.sent.at(-1) as {id:number};w.emit({type:'rpc-result',id:req.id,value:{executionId:'7',pid:40,pgid:40}});const run=await opening,out:string[]=[];run.start.executionId='7';(c as unknown as {executions:Map<string,{output:(fd:string,b:Uint8Array)=>void}>}).executions.get('7')!.output=(fd,b)=>out.push(`${fd}:${new TextDecoder().decode(b)}`);w.emit({type:'exec-output',executionId:'7',fd:'stdout',bytes:new TextEncoder().encode('/root/agent\n')});w.emit({type:'exec-exit',executionId:'7',pid:40,pgid:40,status:0,signal:null,cause:'exit',truncated:false,outputBytes:12,stdoutCapturedBytes:12,stdoutTotalBytes:12,stdoutTruncated:false,stderrCapturedBytes:0,stderrTotalBytes:0,stderrTruncated:false,escalated:false,leakedPids:[]});await expect(run.completed).resolves.toMatchObject({pid:40,pgid:40,status:0,cause:'exit',stdoutTotalBytes:12,stderrTotalBytes:0});expect(out).toEqual(['stdout:/root/agent\n']);});
 it('removes abort listeners and treats unknown/already-finished abort as idempotent',async()=>{
  const first=ready(),naturalAbort=new AbortController(),opening=first.c.exec('true',{signal:naturalAbort.signal}),startReq=first.w.sent.at(-1) as {id:number;request:{executionId:string}};
  first.w.emit({type:'rpc-result',id:startReq.id,value:{executionId:startReq.request.executionId,pid:50,pgid:50}});const run=await opening;
  first.w.emit({type:'exec-exit',executionId:run.start.executionId,pid:50,pgid:50,status:0,signal:null,cause:'exit',truncated:false,outputBytes:0,stdoutCapturedBytes:0,stdoutTotalBytes:0,stdoutTruncated:false,stderrCapturedBytes:0,stderrTotalBytes:0,stderrTruncated:false,escalated:false,leakedPids:[]});await run.completed;await Promise.resolve();
  const afterCompletion=first.w.sent.length;naturalAbort.abort();await Promise.resolve();expect(first.w.sent).toHaveLength(afterCompletion);
  const unknown=run.abort(),unknownReq=first.w.sent.at(-1) as {id:number};first.w.emit({type:'rpc-error',id:unknownReq.id,error:{code:'ENOENT',message:'already finished'}});await expect(unknown).resolves.toBeUndefined();
  const failed=ready(),failedAbort=new AbortController(),failedOpen=failed.c.exec('bad',{signal:failedAbort.signal}),failedReq=failed.w.sent.at(-1) as {id:number};failed.w.emit({type:'rpc-error',id:failedReq.id,error:{code:'ENOEXEC',message:'cannot start'}});await expect(failedOpen).rejects.toThrow('cannot start');const afterFailure=failed.w.sent.length;failedAbort.abort();await Promise.resolve();expect(failed.w.sent).toHaveLength(afterFailure);
 });
});
