import { useEffect, useRef, useState } from 'react';
import { EditorState } from '@codemirror/state'; import { EditorView, keymap, lineNumbers } from '@codemirror/view';
import { defaultKeymap, history, historyKeymap, indentWithTab } from '@codemirror/commands'; import { oneDark } from '@codemirror/theme-one-dark';
import { cpp } from '@codemirror/lang-cpp'; import { markdown } from '@codemirror/lang-markdown'; import { javascript } from '@codemirror/lang-javascript'; import { json } from '@codemirror/lang-json';
import { ArrowLeft, Download, Loader2, Save } from 'lucide-react'; import { Link, useBlocker, useParams } from 'react-router-dom'; import { toast } from 'sonner';
import { FsError, gucFs } from '../fs/kernel-fs'; import { normalizePath, parentPath } from '../lib/paths';
import type { FsSnapshot } from '../kernel/protocol';
import { useKernelState } from '../kernel/context';
import { Button } from '../components/ui/button';
import { Dialog } from '../components/Dialog';

function lang(path:string){const x=path.split('.').pop()?.toLowerCase();if(['c','h','cc','cpp','hpp'].includes(x||''))return cpp();if(['md','markdown'].includes(x||''))return markdown();if(['js','jsx','ts','tsx'].includes(x||''))return javascript({typescript:x==='ts'||x==='tsx',jsx:x==='jsx'||x==='tsx'});if(x==='json')return json();return null;}
// os-owned port of c's EditorPage/FileEditor presentation. OPFS, app-runner,
// media clipboard, and agent state are replaced by bounded gucOS reads/writes.
// Saves are snapshot-conditional (kernel-atomic ifUnchanged): a file changed
// by a terminal, a process, or another view since it was opened surfaces a
// conflict dialog instead of being silently clobbered. The snapshot is taken
// BEFORE the read so a write landing between the two at worst produces a
// conservative false conflict, never a silent overwrite. Dirty edits are
// guarded on in-app navigation (useBlocker) and on reload/close (beforeunload).
export default function EditorPage(){const path=normalizePath(useParams()['*']||'');const kernelState=useKernelState();const host=useRef<HTMLDivElement>(null);const view=useRef<EditorView|null>(null);const baseline=useRef('');const snapshot=useRef<FsSnapshot|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [dirty,setDirty]=useState(false);const [binary,setBinary]=useState<Uint8Array|null>(null);const [conflict,setConflict]=useState(false);
 useEffect(()=>{if(kernelState.status!=='ready')return;let dead=false;setLoading(true);setError('');setDirty(false);setConflict(false);snapshot.current=null;void (async()=>{const st=await gucFs.stat(path);if(!st)throw new FsError('ENOENT',`read ${path}: ENOENT`);const bytes=await gucFs.readBytes(path,2*1024*1024);if(dead)return;snapshot.current={mtimeMs:st.mtimeMs,size:st.size};if(bytes.subarray(0,8192).includes(0)){setBinary(bytes);setLoading(false);return;}const text=new TextDecoder('utf-8',{fatal:true}).decode(bytes);baseline.current=text;const extensions=[history(),lineNumbers(),keymap.of([indentWithTab,...defaultKeymap,...historyKeymap]),oneDark,EditorView.lineWrapping,EditorView.updateListener.of(u=>{if(u.docChanged)setDirty(u.state.doc.toString()!==baseline.current);}),EditorView.theme({'&':{height:'100%',fontSize:'13px'},'.cm-scroller':{fontFamily:'ui-monospace,Menlo,monospace'}})];const l=lang(path);if(l)extensions.push(l);if(host.current){view.current=new EditorView({state:EditorState.create({doc:text,extensions}),parent:host.current});}setLoading(false);})().catch(e=>{if(dead)return;setError(e instanceof Error?e.message:String(e));setLoading(false);});return()=>{dead=true;view.current?.destroy();view.current=null;};},[path,kernelState.status]);
 const save=async(force=false)=>{if(!view.current)return;const text=view.current.state.doc.toString();try{const written=await gucFs.write(path,text,force||!snapshot.current?undefined:{ifUnchanged:snapshot.current});snapshot.current=written;baseline.current=text;setDirty(view.current.state.doc.toString()!==text);toast.success('Saved');}catch(e){if(e instanceof FsError&&e.code==='ECONFLICT')setConflict(true);else toast.error(String(e));}};
 const blocker=useBlocker(dirty);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const download=()=>{if(!binary)return;const url=URL.createObjectURL(new Blob([binary.slice().buffer as ArrayBuffer]));const a=document.createElement('a');a.href=url;a.download=path.split('/').pop()||'file';a.click();URL.revokeObjectURL(url);};
 return <div className="flex-1 flex flex-col overflow-hidden" data-testid="editor-page"><div className="flex items-center gap-2 px-3 md:px-4 py-1.5 border-b border-border shrink-0"><Link to={'/files/'+parentPath(path)} data-testid="editor-back" className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="w-4 h-4"/><span className="hidden sm:inline">Back</span></Link><span className="text-sm font-medium truncate flex-1">{path.split('/').pop()}</span>{binary?<Button variant="outline" size="sm" onClick={download}><Download/><span className="hidden sm:inline">Download</span></Button>:<Button size="sm" disabled={!dirty} onClick={()=>void save()}><Save/>Save</Button>}</div>{loading&&<div className="flex-1 flex items-center justify-center text-muted-foreground"><Loader2 className="w-5 h-5 animate-spin"/></div>}{error&&<div className="m-3 rounded-lg border border-destructive/50 bg-destructive/10 p-4" data-testid="editor-error"><p className="text-sm text-destructive">{error}</p><Link to={'/files/'+parentPath(path)} className="text-sm underline text-destructive">Back to folder</Link></div>}{binary&&<div className="m-3 rounded-lg border bg-card p-6 space-y-3 text-center text-sm text-muted-foreground" data-testid="editor-binary">Binary file ({binary.length} bytes). Download is available; text editing is disabled.</div>}<div ref={host} className={`flex-1 min-h-0 overflow-hidden ${loading||error||binary?'hidden':''}`}/>
 <Dialog open={conflict} title="File changed on disk" description={`${path.split('/').pop()} was modified outside this editor after it was opened. Overwrite permanently replaces those changes with this editor's version. Cancel keeps the file as it is on disk — reopen it to load that version.`} destructive confirmLabel="Overwrite" onCancel={()=>setConflict(false)} onConfirm={()=>{setConflict(false);void save(true);}}/>
 <Dialog open={blocker.state==='blocked'} title="Discard unsaved changes?" description={`${path.split('/').pop()} has unsaved changes. Leaving this page discards them permanently.`} destructive confirmLabel="Discard" onCancel={()=>blocker.reset?.()} onConfirm={()=>blocker.proceed?.()}/></div>;
}
