// os-owned port of c's FilesPage presentation. OPFS/agent/run dependencies are
// replaced with the typed gucOS filesystem adapter; no c runtime is imported.
import React,{useCallback,useEffect,useRef,useState} from 'react';
import {ChevronRight,Download,File as FileIcon,FilePlus,Folder,FolderPlus,HardDrive,Loader2,Pencil,Trash2,Upload} from 'lucide-react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {toast} from 'sonner';
import {Button} from '../components/ui/button';
import {Dialog} from '../components/Dialog';
import {RowMenu} from '../components/RowMenu';
import {FsError,gucFs} from '../fs/kernel-fs';
import {useKernelState} from '../kernel/context';
import type {FsEntry} from '../kernel/protocol';
import {formatBytes,joinPath,normalizePath,validName} from '../lib/paths';

function Breadcrumbs({path}:{path:string}){const seg=path.split('/').filter(Boolean);return <nav className="flex items-center gap-1 min-w-0 overflow-x-auto" data-testid="breadcrumbs"><Link to="/files" title="Filesystem root" className="text-sm text-muted-foreground hover:text-foreground shrink-0">/</Link>{seg.map((s,i)=>{const target='/files/'+seg.slice(0,i+1).join('/'),last=i===seg.length-1;return <React.Fragment key={target}><ChevronRight className="w-3.5 h-3.5 text-muted-foreground shrink-0"/>{last?<span className="text-sm font-medium truncate">{s}</span>:<Link to={target} className="text-sm text-muted-foreground hover:text-foreground shrink-0">{s}</Link>}</React.Fragment>;})}</nav>}
function NameInputRow({kind,initial='',onCommit,onCancel}:{kind:'file'|'folder';initial?:string;onCommit:(v:string)=>void;onCancel:()=>void}){const [value,setValue]=useState(initial),ref=useRef<HTMLInputElement>(null);useEffect(()=>{ref.current?.focus();ref.current?.select();},[]);return <div className="flex items-center gap-2 px-3 py-2"><span className="text-muted-foreground shrink-0">{kind==='file'?<FileIcon className="w-4 h-4"/>:<Folder className="w-4 h-4"/>}</span><input ref={ref} value={value} onChange={e=>setValue(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')onCommit(value.trim());if(e.key==='Escape')onCancel();}} placeholder={kind==='file'?'new-file.c':'new-folder'} data-testid="name-input" className="flex-1 min-w-0 h-8 px-2 text-sm rounded-md border border-input bg-background outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50"/><Button variant="ghost" size="xs" onClick={()=>onCommit(value.trim())}>Save</Button><Button variant="ghost" size="xs" onClick={onCancel}>Cancel</Button></div>}
export default function FilesPage(){const path=normalizePath(useParams()['*']||''),nav=useNavigate(),kernel=useKernelState(),upload=useRef<HTMLInputElement>(null);const [entries,setEntries]=useState<FsEntry[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[creating,setCreating]=useState<'file'|'folder'|null>(null),[renaming,setRenaming]=useState<string|null>(null),[deleting,setDeleting]=useState<FsEntry|null>(null);
 // Overwriting is as destructive as deleting, so it gets the same dialog:
 // every write here is exclusive/noReplace first, and an EEXIST refusal
 // becomes a confirmation carrying the overwrite continuation.
 const [replacing,setReplacing]=useState<{names:string[];description:string;run:()=>Promise<void>}|null>(null);
 const load=useCallback(async()=>{try{setEntries((await gucFs.list(path)).sort((a,b)=>a.kind===b.kind?a.name.localeCompare(b.name):a.kind==='directory'?-1:1));setError('');}catch(e){setError(e instanceof Error?e.message:String(e));setEntries(null);}},[path]);useEffect(()=>{setEntries(null);setCreating(null);setRenaming(null);if(kernel.status==='ready')void load();},[load,kernel.status]);
 const create=async(kind:'file'|'folder',name:string)=>{setCreating(null);if(!name)return;if(!validName(name)){toast.error(`Invalid name: ${name}`);return;}try{const p=joinPath(path,name);if(kind==='folder'){await gucFs.mkdir(p);await load();}else{try{await gucFs.write(p,'',{exclusive:true});nav('/edit/'+p);}catch(e){if(e instanceof FsError&&e.code==='EEXIST')setReplacing({names:[name],description:`A file named ${name} already exists here. Creating it again permanently erases its current contents.`,run:async()=>{await gucFs.write(p,'');nav('/edit/'+p);}});else throw e;}}}catch(e){toast.error(String(e));}};
 const rename=async(entry:FsEntry,name:string)=>{setRenaming(null);if(!name||name===entry.name)return;if(!validName(name)){toast.error(`Invalid name: ${name}`);return;}const from=joinPath(path,entry.name),to=joinPath(path,name);setBusy(true);try{await gucFs.rename(from,to,{noReplace:true});await load();}catch(e){if(e instanceof FsError&&e.code==='EEXIST')setReplacing({names:[name],description:`${name} already exists here. Renaming ${entry.name} onto it permanently erases the existing ${name}.`,run:async()=>{setBusy(true);try{await gucFs.rename(from,to);await load();}catch(x){toast.error(String(x));}finally{setBusy(false);}}});else toast.error(String(e));}finally{setBusy(false);}};
 const remove=async()=>{const e=deleting;if(!e)return;setDeleting(null);setBusy(true);try{await gucFs.remove(joinPath(path,e.name),e.kind==='directory');await load();}catch(x){toast.error(String(x));}finally{setBusy(false);}};
 const download=async(e:FsEntry)=>{try{const p=joinPath(path,e.name),st=await gucFs.stat(p);if(!st||st.kind!=='file')throw new Error('File no longer exists');const picker=(window as Window&{showSaveFilePicker?:(o:{suggestedName:string})=>Promise<{createWritable():Promise<{write(b:Uint8Array):Promise<void>;close():Promise<void>}>}>}).showSaveFilePicker;if(picker){const w=await(await picker({suggestedName:e.name})).createWritable();for(let off=0;off<st.size;off+=4194304)await w.write(await gucFs.readRange(p,off,Math.min(4194304,st.size-off)));await w.close();return;}if(st.size>64*1024*1024)throw new Error('Large downloads require Save File support in this browser');const parts:BlobPart[]=[];for(let off=0;off<st.size;off+=4194304)parts.push((await gucFs.readRange(p,off,Math.min(4194304,st.size-off))).slice().buffer);const url=URL.createObjectURL(new Blob(parts));try{const a=document.createElement('a');a.href=url;a.download=e.name;a.click();}finally{setTimeout(()=>URL.revokeObjectURL(url),0);}}catch(x){toast.error(String(x));}};
 const files=async(list:FileList|null)=>{if(!list?.length)return;setBusy(true);const collisions:File[]=[];for(const f of Array.from(list)){try{await gucFs.write(joinPath(path,f.name),f,{exclusive:true});}catch(e){if(e instanceof FsError&&e.code==='EEXIST')collisions.push(f);else toast.error(`${f.name}: ${String(e)}`);}}setBusy(false);await load();if(collisions.length){const names=collisions.map(f=>f.name);setReplacing({names,description:`${names.length===1?`A file named ${names[0]}`:`${names.length} files (${names.join(', ')})`} already exist${names.length===1?'s':''} here. Uploading replaces the existing contents permanently.`,run:async()=>{setBusy(true);for(const f of collisions){try{await gucFs.write(joinPath(path,f.name),f);}catch(e){toast.error(`${f.name}: ${String(e)}`);}}setBusy(false);await load();}});}};
 return <div className="flex-1 flex flex-col overflow-hidden" data-testid="files-page"><div className="flex items-center justify-between gap-2 px-3 md:px-4 py-2 border-b border-border shrink-0"><Breadcrumbs path={path}/><div className="flex items-center gap-1 shrink-0"><Button variant="ghost" size="icon-sm" title="New file" data-testid="new-file-button" onClick={()=>{setRenaming(null);setCreating('file');}}><FilePlus/></Button><Button variant="ghost" size="icon-sm" title="New folder" data-testid="new-folder-button" onClick={()=>{setRenaming(null);setCreating('folder');}}><FolderPlus/></Button><Button variant="ghost" size="icon-sm" title="Upload files" data-testid="upload-button" onClick={()=>upload.current?.click()}><Upload/></Button><input ref={upload} type="file" multiple className="hidden" data-testid="upload-input" onChange={e=>{void files(e.target.files);e.target.value='';}}/></div></div>
 <div className="flex-1 overflow-y-auto"><div className="max-w-3xl mx-auto" data-testid="file-list">{error&&<div className="m-3 rounded-lg border border-destructive/50 bg-destructive/10 p-4" data-testid="files-error"><p className="text-sm text-destructive">{error}</p><Link to="/files/root" className="text-sm underline text-destructive">Back to home</Link></div>}{creating&&<NameInputRow kind={creating} onCommit={v=>void create(creating,v)} onCancel={()=>setCreating(null)}/>} {entries===null&&!error&&<div className="px-4 py-12 flex justify-center text-muted-foreground"><Loader2 className="w-5 h-5 animate-spin"/></div>}{entries?.length===0&&!creating&&!error&&<div className="px-4 py-12 text-center text-sm text-muted-foreground" data-testid="files-empty">Empty directory. Create a file or upload something.</div>}<ul className="divide-y divide-border">{entries?.map(entry=>{const p=joinPath(path,entry.name);if(renaming===entry.name)return <li key={entry.name}><NameInputRow kind={entry.kind==='file'?'file':'folder'} initial={entry.name} onCommit={v=>void rename(entry,v)} onCancel={()=>setRenaming(null)}/></li>;return <li key={entry.name} className="relative flex items-center gap-2 px-3 py-1 hover:bg-accent/50" data-testid="file-row"><Link to={(entry.kind==='directory'?'/files/':'/edit/')+p} className="flex items-center gap-2 min-w-0 flex-1 py-1.5"><span className="text-muted-foreground shrink-0">{entry.kind==='directory'?<Folder className="w-4 h-4"/>:<FileIcon className="w-4 h-4"/>}</span><span className="text-sm truncate">{entry.name}</span></Link><span className="text-xs text-muted-foreground shrink-0 w-16 text-right hidden sm:block">{entry.kind==='file'?formatBytes(entry.size):''}</span><RowMenu triggerLabel="Actions" triggerTestId={`entry-menu-${entry.name}`} items={[{icon:<Pencil className="w-4"/>,label:'Rename',onSelect:()=>setRenaming(entry.name)},...(entry.kind==='file'?[{icon:<Download className="w-4"/>,label:'Download',onSelect:()=>void download(entry)}]:[]),{icon:<Trash2 className="w-4"/>,label:'Delete',destructive:true,onSelect:()=>setDeleting(entry)}]}/></li>;})}</ul></div></div>
 <footer className="flex items-center justify-between px-3 md:px-4 py-1.5 border-t border-border shrink-0 safe-bottom"><span className="text-xs text-muted-foreground flex items-center gap-1.5" data-testid="storage-usage"><HardDrive className="w-3.5 h-3.5"/>gucOS filesystem</span><span className="text-xs text-muted-foreground flex items-center gap-1.5">{busy&&<Loader2 className="w-3.5 h-3.5 animate-spin"/>}inside the kernel image</span></footer>
 <Dialog open={deleting!==null} title={`Delete ${deleting?.name??''}?`} description={deleting?.kind==='directory'?'The folder and everything inside it will be permanently deleted from gucOS.':'The file will be permanently deleted from gucOS.'} destructive confirmLabel="Delete" onCancel={()=>setDeleting(null)} onConfirm={()=>void remove()}/>
 <Dialog open={replacing!==null} title={replacing&&replacing.names.length>1?`Replace ${replacing.names.length} existing files?`:`Replace ${replacing?.names[0]??''}?`} description={replacing?.description} destructive confirmLabel="Replace" onCancel={()=>setReplacing(null)} onConfirm={()=>{const r=replacing;setReplacing(null);if(r)void r.run().catch(e=>toast.error(String(e)));}}/></div>;
}
