// os-owned presentation copy of c's ProcessesPage, backed by real gucOS ps/signal/surface events.
import { useCallback,useEffect,useState } from 'react';
import { Cpu,Eye,RefreshCw,Square } from 'lucide-react';
import { toast } from 'sonner';
import { useKernel,useKernelState } from '../kernel/context';
import type { ProcessInfo } from '../kernel/protocol';
import { surfaceStore } from '../kernel/surface-store';
import { cn } from '../lib/utils';

function ProcessRow({p,onKill}:{p:ProcessInfo;onKill:(pid:number)=>void}){const [open,setOpen]=useState(false),running=p.state==='running';return <div className="border-b border-border" data-testid="process-row" data-pid={p.pid}>
 <div className="flex items-center gap-3 px-3 md:px-4 py-2.5"><span className="font-mono text-xs text-muted-foreground tabular-nums w-12 shrink-0" data-testid="process-pid">{p.pid}</span><button onClick={()=>setOpen(v=>!v)} className="min-w-0 flex-1 text-left" title="Show process details" data-testid="process-toggle"><div className="font-mono text-sm truncate" title={p.command}>{p.command}</div><div className="text-[11px] text-muted-foreground truncate"><span className={cn('font-medium',running?'text-primary':p.state==='zombie'?'text-muted-foreground':'text-destructive')} data-testid="process-status">{p.state}</span>{' · '}ppid {p.ppid}{p.controllingTerminal?' · interactive':''}</div></button>{p.surfaces.length>0&&<button onClick={()=>surfaceStore.show(p.surfaces[0].id)} className="flex items-center gap-1 text-xs px-2 py-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted/50 transition-colors shrink-0" title="View graphical process" data-testid="process-view"><Eye className="w-3.5 h-3.5"/><span className="hidden sm:inline">View</span></button>}{p.pid!==1&&running&&<button onClick={()=>onKill(p.pid)} className="flex items-center gap-1 text-xs px-2 py-1 rounded-md text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors shrink-0" title="Kill process" data-testid="process-kill"><Square className="w-3.5 h-3.5"/><span className="hidden sm:inline">Kill</span></button>}</div>
 {open&&<div className="mx-3 md:mx-4 mb-2.5 rounded bg-muted/40 p-2 text-[11px] text-muted-foreground" data-testid="process-output"><div>pgid {p.pgid} · sid {p.sid} · cwd {p.cwd}</div>{p.surfaces.length===0?<div>(no graphical surface)</div>:p.surfaces.map(s=><div key={s.id}>surface {s.id}: {s.title||'(untitled)'} · {s.width}×{s.height} · {s.transport}</div>)}</div>}
 </div>}
export default function ProcessesPage(){const kernel=useKernel(),state=useKernelState();const [ps,setPs]=useState<ProcessInfo[]>([]),[error,setError]=useState('');const load=useCallback(async()=>{if(state.status!=='ready')return;try{setPs(await kernel.processes());setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}},[kernel,state.status]);useEffect(()=>{void load();return kernel.subscribe(e=>{if(e.type==='process-changed')setPs(e.processes);});},[kernel,load]);const kill=async(pid:number)=>{try{await kernel.signal(pid,15);await load();}catch(e){toast.error(String(e));}};const running=ps.filter(p=>p.state==='running').length;return <div className="flex-1 flex flex-col overflow-hidden" data-testid="process-page"><div className="flex items-center gap-2 px-3 md:px-4 py-1.5 border-b border-border shrink-0"><Cpu className="w-4 h-4 text-muted-foreground shrink-0"/><span className="text-sm font-medium flex-1">Processes{running>0&&<span className="ml-2 text-xs text-primary" data-testid="process-running-count">{running} running</span>}</span><button onClick={()=>void load()} className="flex items-center gap-1 text-xs px-2 py-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted/50" title="Refresh"><RefreshCw className="w-3.5 h-3.5"/><span className="hidden sm:inline">Refresh</span></button></div>{error&&<p className="text-destructive p-4">{error}</p>}<div className="flex-1 overflow-y-auto">{!error&&ps.length===0?<p className="text-sm text-muted-foreground text-center py-12 px-4" data-testid="process-empty">No processes. Programs started from the terminal appear here while they execute, and graphical programs can be reopened.</p>:<div className="max-w-3xl mx-auto">{ps.map(p=><ProcessRow key={p.pid} p={p} onKill={pid=>void kill(pid)}/>)}</div>}</div></div>}
