import { StrictMode } from 'react'; import { createRoot } from 'react-dom/client'; import { ThemeProvider } from 'next-themes'; import App from './App'; import { KernelProvider } from './kernel/context'; import './styles.css';
window.__osState='booting';window.__terminals=new Map();window.__terminalInput=(id,data)=>import('./kernel/kernel-client').then(({kernelClient})=>kernelClient.terminalInput(id,data));
window.__kernelReadRange=(path,offset,length)=>import('./kernel/kernel-client').then(({kernelClient})=>kernelClient.read(path,offset,length));window.__kernelStat=path=>import('./kernel/kernel-client').then(({kernelClient})=>kernelClient.stat(path));
// Bounded diagnostic history used by process UI/browser acceptance; never retain more than 128 snapshots.
window.__processEvents=[];void import('./kernel/kernel-client').then(({kernelClient})=>kernelClient.subscribe(event=>{if(event.type==='process-changed'){window.__processEvents.push(structuredClone(event.processes));if(window.__processEvents.length>128)window.__processEvents.splice(0,window.__processEvents.length-128)}}));window.__kernelProcesses=()=>import('./kernel/kernel-client').then(({kernelClient})=>kernelClient.processes());
window.__kernelExec=(command,timeoutMs)=>import('./kernel/kernel-client').then(async({kernelClient})=>{let stdout='',stderr='';const run=await kernelClient.exec(command,{timeoutMs,onOutput:(fd,b)=>{const text=new TextDecoder().decode(b);if(fd==='stdout')stdout+=text;else stderr+=text}});return{start:run.start,exit:await run.completed,stdout,stderr}});
if ('serviceWorker' in navigator) addEventListener('load',()=>navigator.serviceWorker.register('/sw.js').catch(e=>console.error('gucOS service-worker registration failed:',e)));
if (navigator.storage?.persist) void navigator.storage.persist().then(granted=>{localStorage.setItem('gucos2:storage-persisted',String(granted));dispatchEvent(new CustomEvent('gucos2:storage-persistence',{detail:granted}))}).catch(e=>{localStorage.setItem('gucos2:storage-persisted','error');dispatchEvent(new CustomEvent('gucos2:storage-persistence',{detail:'error'}));console.warn('gucOS persistent-storage request failed:',e)});
const hostRuntime=document.createElement('script');hostRuntime.src=`/runtime/${__RUNTIME_GENERATION__}/host.js`;hostRuntime.onerror=()=>console.error('gucOS audio host runtime failed to load');document.head.appendChild(hostRuntime);
createRoot(document.getElementById('root')!).render(<StrictMode><ThemeProvider attribute="class" defaultTheme="system" enableSystem><KernelProvider><App/></KernelProvider></ThemeProvider></StrictMode>);
